### ISSUE TITLE
Kohi Episode 29 - Crash

### ISSUE THREAD

**Issue by WongMan58** [travisvroman/kohi#111] opened 2022-12-20 23:38 UTC
**Describe the bug**
I know I'm a bit behind when it comes to the series since I just started a few weeks ago, but after episode 29: https://www.youtube.com/watch?v=yc40ixalLtU&list=PLv8Ddw9K0JPg1BEO-RS-0MYs423cvLVtj&index=32
and even the fix episode 29.1, I'm getting this error:

[WARN]:  Unable to find suitable memory type!
[ERROR]: Unable to create vulkan buffer because the required memory type index was not found.
[ERROR]: Vulkan buffer creation failed for object shader.
[ERROR]: Error loading built-in basic_lighting shader.
[FATAL]: Renderer backend failed to initialize. Shutting down.
[FATAL]: Failed to initialize renderer. Aborting application.
[FATAL]: Application failed to create!.

I've tried download the repo at for episode 29, but I've still been getting this error. How can I fix this?

**To Reproduce**
1. Build project
2. Run project
3. Scroll down on console to see error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
[vulkaninfo.txt](https://github.com/travisvroman/kohi/files/10273353/vulkaninfo.txt)

- GPU: Nvidia Geforce GT 710
- Vulkan SDK Version: 1.3.216.0

My vulkaninfo is attached to this report

**Comment by WongMan58** [comment] 2022-12-21 00:55
NOTE: Everything worked before episode 29

**Comment by travisvroman** [comment] 2022-12-22 20:34
Thank you for reporting this!

I think this came up once before, but I couldn't find an issue on it (I'm guessing it was a comment, or something). Anyway, this issue directly stems from the addition of the properties `VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT | VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT` being required. This does indeed get fixed later on in the series. Videos 34 and 34.1 touch on this, where we detect if this is supported by the card and handle it appropriately.

Going to close this as it's not a bug.

**Closed by travisvroman** 2022-12-22 20:34 UTC
Labels: bug
