### ISSUE TITLE
Calling vkBeginCommandBuffer on an active command buffer

### ISSUE THREAD

**Issue by junglie85** [travisvroman/kohi#4] opened 2021-08-17 11:05 UTC
I've been following along with the series and after the screen clearing episode get the following error:

```
[ERROR]: Validation Error: [ VUID-vkBeginCommandBuffer-commandBuffer-00049 ] Object 0: handle = 0x7fdc5087b0e8, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x84029a9f | Calling vkBeginCommandBuffer() on active VkCommandBuffer 0x7fdc5087b0e8[] before it has completed. You must check command buffer fence before this call. The Vulkan spec states: commandBuffer must not be in the recording or pending state (https://vulkan.lunarg.com/doc/view/1.2.182.0/mac/1.2-extensions/vkspec.html#VUID-vkBeginCommandBuffer-commandBuffer-00049)
```

I wondered whether this is because I'm implementing from scratch rather than copy/pasting your implementation. However, I get this same error when running a fork of this repo. I don't know what's going on here and whether it is a general error or related to macOS and MoltenVK.

**Comment by travisvroman** [comment] 2021-08-29 16:44
Someone else in Discord ran into this, and it was because the fence reset logic was incorrect in their local copy. I'd suggest having a look there and compare it to what's in the current repo.

**Comment by JadTala** [comment] 2021-08-31 17:21
I've got the same issue on Linux and it also happens on a fresh git clone, no such issue on Windows.
Meanwhile on macOS I get these three repeating validation errors:

```[ERROR]: Validation Error: [ VUID-vkQueueSubmit-pCommandBuffers-00071 ] Object 0: handle = 0x7f7951839c18, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x2e2f4d65 | vkQueueSubmit(): pSubmits[0].pCommandBuffers[0] VkCommandBuffer 0x600002430358[] is already in use and is not marked for simultaneous use. The Vulkan spec states: If any element of the pCommandBuffers member of any element of pSubmits was not recorded with the VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT, it must not be in the pending state (https://vulkan.lunarg.com/doc/view/1.2.170.0/mac/1.2-extensions/vkspec.html#VUID-vkQueueSubmit-pCommandBuffers-00071)```

```[ERROR]: Validation Error: [ VUID-vkBeginCommandBuffer-commandBuffer-00049 ] Object 0: handle = 0x6000024301b8, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x84029a9f | Calling vkBeginCommandBuffer() on active VkCommandBuffer 0x6000024301b8[] before it has completed. You must check command buffer fence before this call. The Vulkan spec states: commandBuffer must not be in the recording or pending state (https://vulkan.lunarg.com/doc/view/1.2.170.0/mac/1.2-extensions/vkspec.html#VUID-vkBeginCommandBuffer-commandBuffer-00049)```

```[ERROR]: Validation Error: [ VUID-vkBeginCommandBuffer-commandBuffer-00049 ] Object 0: handle = 0x6000024301b8, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x84029a9f | Calling vkBeginCommandBuffer() on active VkCommandBuffer 0x6000024301b8[] before it has completed. You must check command buffer fence before this call. The Vulkan spec states: commandBuffer must not be in the recording or pending state (https://vulkan.lunarg.com/doc/view/1.2.170.0/mac/1.2-extensions/vkspec.html#VUID-vkBeginCommandBuffer-commandBuffer-00049)```

**Comment by travisvroman** [comment] 2021-09-01 01:49
I've not run into this on Linux. What distro are you using, and are your GPU drivers up to date? When you say fresh clone, do you mean of the kohi repo?

**Comment by JadTala** [comment] 2021-09-01 09:47
I'm using Arch Linux on a VM with `mesa-git` that has a Vulkan software implementation called lavapipe, but now that I remember it's not a conformant Vulkan implementation, so my issue is probably irrelevant.
The one on macOS happens on my discrete GPU that is an AMD Radeon Pro 5500M.
I indeed mean a fresh clone of the Kohi repo.

**Comment by Drayan** [comment] 2021-11-26 01:25
I had this issue too on my Mac m1, my code is slightly different from the repository but I resolved the issue by doing this :
In vulkan_renderer_begin_frame, I added a wait to the fence for images_in_flight[context.image_index].
It seams that acquireNextImage can return image_index before the semaphore is signaled. As the command buffer is sort of linked with the image index, if the GPU didn't finished before starting to write on the commandBuffer, we get the errors above. :)

**Comment by travisvroman** [comment] 2022-02-01 12:56
@Drayan Would you mind putting in a pull request with your changes? I'm not able to reproduce this and would like to see what you did to help me understand the difference.

**Comment by travisvroman** [comment] 2022-04-30 23:13
@Drayan Just following up on this. Did you want to put up a PR with this? I'll close this if not. Thank you!

**Comment by travisvroman** [comment] 2022-08-28 00:13
Closing due to inactivity.

**Closed by travisvroman** 2022-08-28 00:13 UTC
