### ISSUE TITLE
memset doesn't work with i32

### ISSUE THREAD

**Issue by MohammadResli** [travisvroman/kohi#83] opened 2022-08-31 14:50 UTC
https://github.com/travisvroman/kohi/blob/c8fd2cdbf986038f21f89392642b76807278bb12/engine/src/platform/platform_win32.c#L170

Hi, memset doesn't work with i32 correctly, 
if you want to fill an array of integers with 1 using the platform_set_memory, then you will get an array filled with 16843009  instead, 

see this sample code to regenerate the bug, https://ideone.com/nf3EYB

please use for loop instead.

**Comment by josephofthebread** [comment] 2022-10-20 20:37
Man, please, take a look at [this page](https://en.cppreference.com/w/c/string/byte/memset)
Everything is correct

**Comment by travisvroman** [comment] 2023-01-09 01:53
Thanks for submitting this! @josephofthebread is correct though. This isn't used to fill an array and shouldn't be treated as such. This works as intended. Closing.

**Closed by travisvroman** 2023-01-09 01:53 UTC
