### ISSUE TITLE
[BUG] './libengine.dylib' (no such file), './libengine.dylib' (no such file)

### ISSUE THREAD

**Issue by Lu-TheCoder** [travisvroman/kohi#193] opened 2023-10-04 09:51 UTC
**Describe the bug**
After running the build-all.sh script on macOS running the executable through the Xcode debugger yields a library not found error for libengine.dylib, and manually running the app with ./bin/testbed yields the same error..

**To Reproduce**
1. Go to 'root project directory in Xcode'
2. open the terminal in Xcode
3. type 'sh build-release.sh Darwin' in the terminal
4. once the executable has successuffy complied without errors
5. type './bin/testbad' in the terminal to run the app or run it through the Xcode debugger directly instead
6. the error will be displayed in the terminal

**Expected behavior**
The app should open and run as expected since it compiled successfully 

**Screenshots**
here is the screenshot of the error message from the terminal :

<img width="972" alt="Screenshot 2023-10-04 at 11 49 24" src="https://github.com/travisvroman/kohi/assets/90724319/32cbed72-55f9-4940-a230-d35e0ed6c96c">

I have vulkan installed on my machine and it also says libvulkan.1.dylib is not not found?

<img width="969" alt="Screenshot 2023-10-04 at 11 53 45" src="https://github.com/travisvroman/kohi/assets/90724319/94baaf87-1b45-46c9-bbf3-1e0813b8c3b5">

How can I fix it?

**Additional context**
If this is not a bug kindly, show me what I am missing and what I need to do for the executable to find the libengine.dylib since they are all compiled and in the same bin directly, but still the testbed executable doesn't find it on launch.

**Comment by sdrpa** [comment] 2023-10-05 09:18
A quick fix to run the engine on macOS from VSCode is to create a sym link to ```libvulkan.1.dylib```.
In your case you can do something like this:
```
cd /Users/luthecoder/Downloads/kohi-main/bin
ln -s /Users/luthecoder/VulkanSDK/1.3.250.1/macOS/lib/libvulkan.1.dylib libvulkan.1.dylib
```

The problem is that ```libengine.dylib``` is looking for ```libvulkan.1.dylib``` in the current directory (```/Users/luthecoder/Downloads/kohi-main/bin```) but it isn't there. You can inspect the paths with ```otool -L libengine.dylib```

```
% otool -L libengine.dylib
libengine.dylib:
	@rpath/libengine.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libvulkan.1.dylib (compatibility version 1.0.0, current version 1.3.250)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 2483.0.0)
	/System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore (compatibility version 1.2.0, current version 1.11.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1336.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 2048.1.255)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 2048.1.255)
```

**Comment by travisvroman** [comment] 2023-10-05 23:24
Thanks for reporting this! 

This is likely because kohi is setup to be run from the `bin` folder (i.e. the working directory needs to be `bin`, not the root folder). Have you tried that to see if it solves this issue?

**Comment by Lu-TheCoder** [comment] 2023-10-05 23:42
Thanks @sdrpa and @travisvroman 

Both your solutions work indeed

however what I did prior to your responses was I manually copy pasted the libraries that couldn't be found such as libvulkan.1.dylib. 

This is how the bin folder looked after I just copy pasted the 5 libraries that couldn't be found:

<img width="260" alt="Screenshot 2023-10-06 at 01 32 16" src="https://github.com/travisvroman/kohi/assets/90724319/ccb2e741-620b-4807-ad8b-78890b72d5d8">

after adding those additional libraries to the bin folder it worked when I ran it from the VS Code debugger 
(Via the `Launch testbed`)

but this issue is fixed if I just cd directly into the `bin folder` and run `./testbed instead` like you suggested from terminal.

however seems the copy pasted solution I used is only necessary when I try to run the VSCode Debugger (F5)..

**Comment by travisvroman** [comment] 2023-11-27 00:28
Yeah, if your working directory is in the `bin` folder this works as intended. Closing this issue.

**Closed by travisvroman** 2023-11-27 00:28 UTC
Labels: bug
